package it.wldt.augmentation.event;

import it.wldt.core.event.WldtEvent;
import it.wldt.exception.EventBusException;

import java.util.Map;

/**
 * Authors:
 *          Leonardo Micelli (leonardomicelli@gmail.com)
 * Date: 20/06/2025
 * Project: White Label Digital Twin Java Framework - (whitelabel-digitaltwin)
 *
 * Abstract WLDTEvent used to describe and characterize any augmentation event that can trigger or be generated by an
 * AugmentationFunction.
 */
public abstract class AugmentationEvent<T> extends WldtEvent<T> {
    public static final String EVENT_BASIC_TYPE = "dt.augmentation.event";

    public AugmentationEvent(String type) throws EventBusException {
        super(type);
        adaptEventType();
    }

    public AugmentationEvent(String type, T body) throws EventBusException {
        super(type, body);
        adaptEventType();
    }

    public AugmentationEvent(String type, T body, Map<String, Object> metadata) throws EventBusException {
        super(type, body, metadata);
        adaptEventType();
    }

    private void adaptEventType(){
        if(this.getType() != null)
            this.setType(buildEventType(this.getBasicEventType(), this.getType()));
    }

    public static String buildEventType(String basicEventType, String eventType){
        if(eventType != null)
            return String.format("%s.%s", basicEventType, eventType);
        else
            return null;
    }

    abstract protected String getBasicEventType();
}
